package com.kakfa.db;

import java.util.Objects;

/**
 * A DbBike is a Bike, but also has an id.
 *
 * This is the data model we have for a bike in the database.
 *
 * This class was mostly auto-generated by the IDE,
 * except the equals method which needed help delegating
 * to the parent class Bike.
 *
 * @author damon.berry
 * @since  October 2019
 */
public class DbBike extends Bike {

    protected int id;

    public DbBike(int id, String name, boolean bmx) {
        super(name, bmx);
        this.id = id;
    }

    public int getId() {
        return id;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + Objects.hash(id);
        return result;
    }

    @Override
    public boolean equals(Object obj) {

        if (this == obj) {
            return true;
        }

        if (obj instanceof DbBike) {
            DbBike other = (DbBike) obj;
            return id == other.id && super.equals(obj);
        }
        else if (obj instanceof Bike) {
            Bike other = (Bike) obj;
            return super.equals(other);
        }
        else {
            return false;
        }
    }

    @Override
    public String toString() {
        return "DbBike [id=" + id + ", name=" + name + ", bmx=" + bmx + "]";
    }

}
