#!/usr/bin/env bash
# drop the tables generated by the functional tests
#
# add new tables here:
#
FUNKY_TABLES="bikes"
for table in $(echo "$FUNKY_TABLES"); do echo "dropping table $table"; ./psql-user.sh -c "drop table $table"; echo; done

# run the func tests
#
./gradlew clean funcTest
