/*
 * This Java source file was (mostly) generated by the Gradle 'init' task.
 */
package com.kakfa;

import org.junit.Test;
import static org.junit.Assert.assertNotNull;

/**
 * Simple unit test of our hello world application.
 * 
 * @author damon.berry
 * @since  August 2019
 */
public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
