/*
 * This Java source file was (almost entirely) generated by the Gradle 'init' task.
 */
package com.kakfa;

/**
 * Simple hello world application.
 * 
 * @author damon.berry
 * @since  August 2019
 */
public class App {

    public static final String HELLO_WORLD = "Hello world.";

    public String getGreeting() {
        return HELLO_WORLD;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
