/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kakfa;

public class App {

    public static final String HELLO_WORLD = "Hello world.";

    public String getGreeting() {
        return HELLO_WORLD;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
